openapi: 3.0.0
info:
  title: Pet Store API
  version: 0.0.0
tags: []
paths:
  /pets:
    get:
      operationId: Pets_getAllPets
      parameters:
        - name: filter
          in: query
          required: true
          schema:
            type: string
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
              example:
                - id: 123
                  name: Max
                  age: 3
                  kind: dog
    post:
      operationId: Pets_create
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              example:
                id: 123
                name: Max
                age: 3
                kind: dog
        '202':
          description: The request has been accepted for processing, but processing has not yet completed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
            example:
              id: 123
              name: Max
              age: 3
              kind: dog
  /pets/{id}:
    get:
      operationId: Pets_getPetById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              example:
                id: 123
                name: Max
                age: 23
                kind: bird
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
  /pets/{petId}:
    put:
      operationId: Pets_updatePet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              example:
                id: 123
                name: Max
                age: 23
                kind: bird
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
            example:
              id: 123
              name: Max
              age: 23
              kind: bird
    delete:
      operationId: Pets_deletePet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /stores:
    get:
      operationId: Stores_list
      parameters:
        - name: filter
          in: query
          required: true
          schema:
            type: string
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Store'
              example:
                - id: 123
                  name: abc store
                  address:
                    street: 123 street
                    city: xyz city
  /stores/{id}:
    get:
      operationId: Stores_read
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
              example:
                id: 123
                name: Max
                address:
                  street: abc street
                  city: xyz city
components:
  schemas:
    Address:
      type: object
      required:
        - street
        - city
      properties:
        street:
          type: string
          minLength: 3
          maxLength: 100
        city:
          type: string
          minLength: 3
          maxLength: 100
      description: This is a simple address model
    InternalServerError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - INTERNAL_SERVER_ERROR
        message:
          type: string
    NotFoundError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - NOT_FOUND
        message:
          type: string
    Pet:
      type: object
      required:
        - id
        - name
        - age
        - kind
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        name:
          type: string
          minLength: 3
          maxLength: 100
        age:
          type: integer
          format: int32
          minimum: 1
          maximum: 100
        kind:
          $ref: '#/components/schemas/petType'
      description: This is a simple pet model
    Store:
      type: object
      required:
        - id
        - name
        - address
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        name:
          type: string
          minLength: 3
          maxLength: 100
        address:
          $ref: '#/components/schemas/Address'
      description: This is a simple store model
    ValidationError:
      type: object
      required:
        - code
        - message
        - details
      properties:
        code:
          type: string
          enum:
            - VALIDATION_ERROR
        message:
          type: string
        details:
          type: array
          items:
            type: string
    petType:
      type: string
      enum:
        - dog
        - cat
        - fish
        - bird
        - reptile
servers:
  - url: https://example.com
    description: Single server endpoint
    variables: {}
